# Generated by Django 5.2.4 on 2025-07-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_negotiationticket_negotiated_by_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('negotiation', 'Under Negotiation'), ('accepted', 'Accepted')], default='draft', max_length=15),
        ),
    ]
